$manifest = @{}
$imgExts = @('.jpg','.jpeg','.png','.gif','.webp')
if (Test-Path "images") {
    Get-ChildItem "images" -Directory | ForEach-Object {
        $folder = $_.Name
        $files = Get-ChildItem $_.FullName -File |
                 Where-Object { $imgExts -contains $_.Extension.ToLower() } |
                 Sort-Object Name |
                 ForEach-Object { "images/$folder/$($_.Name)" }
        if ($files) { $manifest[$folder] = @($files) }
    }
}
$manifest | ConvertTo-Json -Depth 3 | Out-File "manifest.json" -Encoding utf8
Write-Output "manifest.json updated: $($manifest.Count) folders"

# Download CSV from Google Sheets (fallback: local CSV)
$gsUrl = "https://docs.google.com/spreadsheets/d/1n8A-wMmJxdwwFjKDfL1jsj-Llcz3QQDXrHnJ2fNMNJ8/export?format=csv"
Write-Output "Downloading Google Sheets data..."
$csvRaw = $null
try {
    $wc = New-Object System.Net.WebClient
    $wc.Encoding = [System.Text.Encoding]::UTF8
    $csvRaw = $wc.DownloadString($gsUrl)
    Write-Output "Google Sheets OK"
} catch {
    Write-Output "Cannot reach Google Sheets, using local CSV"
    $localCsv = (Get-ChildItem "*.csv" | Where-Object { $_.Name -like "*slide mount*" } | Select-Object -First 1).FullName
    if ($localCsv) {
        $sr = [System.IO.StreamReader]::new($localCsv, [System.Text.Encoding]::UTF8)
        $csvRaw = $sr.ReadToEnd()
        $sr.Close()
    }
}

if (-not $csvRaw) { Write-Output "ERROR: no CSV data"; exit 1 }
if ($csvRaw[0] -eq [char]0xFEFF) { $csvRaw = $csvRaw.Substring(1) }

$csvJson        = $csvRaw | ConvertTo-Json -Compress
$manifestJson   = $manifest | ConvertTo-Json -Depth 3 -Compress
$outPath        = Join-Path (Get-Location).ProviderPath "data.js"

$header = "// Auto-generated by build.ps1 - do not edit manually"
$body   = "window.EMBEDDED_DATA = { csv: " + $csvJson + ", manifest: " + $manifestJson + " };"

Set-Content -Path $outPath -Value @($header, $body) -Encoding UTF8
Write-Output "data.js generated (offline mode ready)"
