$manifest = @{}
$imgExts = @('.jpg','.jpeg','.png','.gif','.webp')
if (Test-Path "images") {
    Get-ChildItem "images" -Directory | ForEach-Object {
        $folder = $_.Name
        $files = Get-ChildItem $_.FullName -File |
                 Where-Object { $imgExts -contains $_.Extension.ToLower() } |
                 Sort-Object Name |
                 ForEach-Object { "images/$folder/$($_.Name)" }
        if ($files) { $manifest[$folder] = @($files) }
    }
}
$manifest | ConvertTo-Json -Depth 3 | Out-File "manifest.json" -Encoding utf8
Write-Output "manifest.json updated: $($manifest.Count) folders"

# ── Generate data.js for offline file:// use ──────────────────────────────
$csvFile = (Get-ChildItem "*.csv" | Where-Object { $_.Name -like "*slide mount*" } | Select-Object -First 1).FullName
$sr = [System.IO.StreamReader]::new($csvFile, [System.Text.Encoding]::UTF8)
$csvRaw = $sr.ReadToEnd(); $sr.Close()
# Strip UTF-8 BOM if present
if ($csvRaw -and $csvRaw[0] -eq [char]0xFEFF) { $csvRaw = $csvRaw.Substring(1) }
$csvJson = $csvRaw | ConvertTo-Json -Compress

$manifestCompact = $manifest | ConvertTo-Json -Depth 3 -Compress
$dataJs = "// Auto-generated by build.ps1 - do not edit manually`nwindow.EMBEDDED_DATA = { csv: $csvJson, manifest: $manifestCompact };"

$outPath = Join-Path (Get-Location).ProviderPath "data.js"
[System.IO.File]::WriteAllText($outPath, $dataJs, [System.Text.UTF8Encoding]::new($false))
Write-Output "data.js generated (offline mode ready)"