# -*- coding: utf-8 -*-
"""
gen_species_plate.py — 由 data.js 內嵌資料抽出「所有種名」，產生種級代表照清單與資料夾。

產出：
  - species_plate.js              供 index.html「種級代表照」讀取（window.SPECIES_PLATE）
  - species_photos/<id>/          每個物種一個資料夾（含 .gitkeep），不覆蓋既有照片

用法： python gen_species_plate.py
"""
import json
import re
import csv
import io
import pathlib
import collections

BASE      = pathlib.Path(__file__).parent
DATA_JS   = BASE / "data.js"
OUT_JS    = BASE / "species_plate.js"
PHOTO_DIR = BASE / "species_photos"

# Windows 檔名不可用字元；另移除 ? 與前後空白
_INVALID = re.compile(r'[\\/:*?"<>|]')


def make_id(genus, species):
    """由屬+種小名組出檔案系統/網址安全的資料夾 id。"""
    sp = species.strip().rstrip("?").strip()
    base = sp if sp else genus.strip()
    base = _INVALID.sub("", base)            # 去掉非法字元
    base = base.replace(" ", "_").strip(" .")
    return base.lower() if base.isascii() else base


def clean_zh(values):
    """從多個中文名挑一個最乾淨、最常見的。"""
    cleaned = []
    for v in values:
        z = re.sub(r"[（(].*?[)）]", "", v)   # 去除 (暫定) (根據序列) 等註記
        z = z.replace("?", "").strip()
        if z:
            cleaned.append(z)
    if not cleaned:
        return ""
    # 優先排除含「疑似/序列」字樣者
    pref = [z for z in cleaned if not re.search(r"疑似|序列", z)]
    pool = pref or cleaned
    return collections.Counter(pool).most_common(1)[0][0]


def load_rows():
    raw = DATA_JS.read_text(encoding="utf-8-sig")
    idx = raw.find("csv: ")
    csv_text, _ = json.JSONDecoder().raw_decode(raw, idx + len("csv: "))
    return list(csv.reader(io.StringIO(csv_text)))


def main():
    rows = load_rows()
    hdr = rows[0]
    gi, spi, zi = hdr.index("Genus"), hdr.index("Species"), hdr.index("中文名")

    # 聚合：key = (genus, species_epithet) → 中文名候選
    agg = collections.OrderedDict()
    for r in rows[1:]:
        if len(r) <= max(gi, spi, zi):
            continue
        g, sp, z = r[gi].strip(), r[spi].strip(), r[zi].strip()
        if not g or not sp:        # 沒有屬或種小名者略過
            continue
        key = (g, sp)
        agg.setdefault(key, [])
        if z:
            agg[key].append(z)

    species = []
    seen_ids = {}
    for (g, sp), zhs in agg.items():
        sid = make_id(g, sp)
        if sid in seen_ids:        # id 撞名 → 加屬名前綴區隔
            sid = (g[:3] + "_" + sid).lower()
        seen_ids[sid] = True
        species.append({
            "id": sid,
            "sci": f"{g} {sp}".strip(),
            "zh": clean_zh(zhs),
        })

    # 排序：庫蠓屬優先，其餘依學名
    species.sort(key=lambda s: (not s["sci"].startswith("Culicoides"), s["sci"].lower()))

    # 寫 species_plate.js
    body = ("// Auto-generated by gen_species_plate.py - do not edit manually\n"
            "window.SPECIES_PLATE = "
            + json.dumps(species, ensure_ascii=False, indent=1) + ";\n")
    OUT_JS.write_text(body, encoding="utf-8")

    # 建立資料夾（不覆蓋既有照片）
    PHOTO_DIR.mkdir(exist_ok=True)
    created = []
    for s in species:
        d = PHOTO_DIR / s["id"]
        if not d.exists():
            d.mkdir(parents=True)
            created.append(s["id"])
        gk = d / ".gitkeep"
        if not gk.exists():
            gk.write_text("", encoding="utf-8")

    print(f"{OUT_JS.name}: {len(species)} 個物種")
    for s in species:
        print(f"  {s['id']:18s} {s['sci']:30s} {s['zh']}")
    if created:
        print(f"\n新建資料夾 {len(created)} 個：{', '.join(created)}")
    else:
        print("\n（資料夾皆已存在）")


if __name__ == "__main__":
    main()
