// Auto-generated by gen_keymatrix.py - do not edit manually
window.KEY_MATRIX = {
 "species": [
  {
   "id": "actoni",
   "sci": "Culicoides actoni",
   "zh": "阿氏庫蠓",
   "photo": "images/Cer17/0.Cer17 Wings.png"
  },
  {
   "id": "arakawae",
   "sci": "Culicoides arakawae",
   "zh": "荒川庫蠓",
   "photo": "images/Cer13/0.Cer13 Wings.png"
  },
  {
   "id": "homotomus",
   "sci": "Culicoides homotomus",
   "zh": "原野庫蠓",
   "photo": "images/Cer21/0.Cer21 Wings.png"
  },
  {
   "id": "jacobsoni",
   "sci": "Culicoides jacobsoni",
   "zh": "雅氏庫蠓",
   "photo": "images/Cer44/0.Cer44 Wings.png"
  },
  {
   "id": "lungchiensis",
   "sci": "Culicoides lungchiensis",
   "zh": "龍溪庫蠓",
   "photo": "images/Cer27/0.Cer27 Wings.png"
  },
  {
   "id": "palpifer",
   "sci": "Culicoides palpifer",
   "zh": "帶鬚庫蠓",
   "photo": null
  },
  {
   "id": "oxystoma",
   "sci": "Culicoides oxystoma",
   "zh": "嗜牛庫蠓",
   "photo": "images/Cer48/0.Cer48 Wings.png"
  },
  {
   "id": "sumatrae",
   "sci": "Culicoides sumatrae",
   "zh": "蘇島庫蠓",
   "photo": "images/Cer33/0.win_4x.png"
  },
  {
   "id": "tainanus",
   "sci": "Culicoides tainanus",
   "zh": "台南庫蠓",
   "photo": "images/Cer7/0.Cer7 Wings.png"
  }
 ],
 "characters": [
  {
   "id": "c_0",
   "region": "Eyes",
   "name": "眼間毛",
   "nameEn": "Interfacetal hairs",
   "type": "cat",
   "note": "bare/pilose",
   "states": [
    "有毛 (pilose)",
    "無毛 (bare)"
   ],
   "values": {
    "actoni": {
     "state": "有毛 (pilose)",
     "raw": "pilose"
    },
    "arakawae": {
     "state": "無毛 (bare)",
     "raw": "bare"
    },
    "homotomus": {
     "state": "無毛 (bare)",
     "raw": "bare"
    },
    "jacobsoni": {
     "state": "無毛 (bare)",
     "raw": "bare"
    },
    "lungchiensis": {
     "state": "無毛 (bare)",
     "raw": "bare"
    },
    "palpifer": {
     "state": "無毛 (bare)",
     "raw": "bare"
    },
    "oxystoma": {
     "state": "無毛 (bare)",
     "raw": "bare"
    },
    "sumatrae": {
     "state": "無毛 (bare)",
     "raw": "bare"
    },
    "tainanus": {
     "state": "無毛 (bare)",
     "raw": "bare"
    }
   }
  },
  {
   "id": "n_1",
   "region": "Antenna",
   "name": "AR 觸角比",
   "nameEn": "Antennal ratio",
   "type": "num",
   "unit": "",
   "note": "0.7–1.5 (台灣種類)",
   "min": 0.82,
   "max": 1.67,
   "pad": 0.034,
   "values": {
    "actoni": {
     "min": 1.27,
     "max": 1.33,
     "raw": "1.27–1.33"
    },
    "arakawae": {
     "min": 1.67,
     "max": 1.67,
     "raw": "1.67"
    },
    "homotomus": {
     "min": 0.82,
     "max": 0.82,
     "raw": "0.82"
    },
    "jacobsoni": {
     "min": 1.07,
     "max": 1.28,
     "raw": "1.07–1.28"
    },
    "lungchiensis": {
     "min": 1.09,
     "max": 1.09,
     "raw": "1.09"
    },
    "palpifer": {
     "min": 1.11,
     "max": 1.11,
     "raw": "1.11"
    },
    "oxystoma": {
     "min": 1.02,
     "max": 1.02,
     "raw": "1.02"
    },
    "sumatrae": {
     "min": 0.99,
     "max": 1.01,
     "raw": "0.99–1.01"
    },
    "tainanus": {
     "min": 1.12,
     "max": 1.12,
     "raw": "1.12"
    }
   }
  },
  {
   "id": "c_2",
   "region": "Palpus",
   "name": "感覺窩",
   "nameEn": "Sensory pit (palpal pit)",
   "type": "cat",
   "note": "有/ 無（感覺毛散布）",
   "states": [
    "有",
    "無"
   ],
   "values": {
    "actoni": {
     "state": "有",
     "raw": "有"
    },
    "arakawae": {
     "state": "有",
     "raw": "有（大深窩）"
    },
    "homotomus": {
     "state": "有",
     "raw": "有（橢圓）"
    },
    "jacobsoni": {
     "state": "有",
     "raw": "有（小窩）"
    },
    "lungchiensis": {
     "state": "無",
     "raw": "無"
    },
    "palpifer": {
     "state": "有",
     "raw": "有（淺窩）"
    },
    "oxystoma": {
     "state": "有",
     "raw": "有（小淺窩）"
    },
    "sumatrae": {
     "state": "有",
     "raw": "有（橢圓淺窩）"
    },
    "tainanus": {
     "state": "有",
     "raw": "有（圓形窩）"
    }
   }
  },
  {
   "id": "n_3",
   "region": "Palpus",
   "name": "PR 觸鬚比",
   "nameEn": "Palpal ratio",
   "type": "num",
   "unit": "",
   "note": "1.0–8.0 (台灣種類)",
   "min": 1.63,
   "max": 3.29,
   "pad": 0.0664,
   "values": {
    "actoni": {
     "min": 2.0,
     "max": 2.69,
     "raw": "2.00–2.69"
    },
    "arakawae": {
     "min": 2.53,
     "max": 2.63,
     "raw": "2.53–2.63"
    },
    "homotomus": {
     "min": 2.71,
     "max": 2.85,
     "raw": "2.71–2.85"
    },
    "jacobsoni": {
     "min": 2.35,
     "max": 2.99,
     "raw": "2.35–2.99"
    },
    "lungchiensis": {
     "min": 2.93,
     "max": 2.93,
     "raw": "2.93"
    },
    "palpifer": {
     "min": 2.57,
     "max": 2.57,
     "raw": "2.57"
    },
    "oxystoma": {
     "min": 1.63,
     "max": 1.63,
     "raw": "1.63"
    },
    "sumatrae": {
     "min": 2.39,
     "max": 3.29,
     "raw": "2.39–3.29"
    },
    "tainanus": {
     "min": 2.28,
     "max": 2.55,
     "raw": "2.28–2.55"
    }
   }
  },
  {
   "id": "n_4",
   "region": "Mouthpart",
   "name": "P/H 喙頭比",
   "nameEn": "Proboscis/head ratio",
   "type": "num",
   "unit": "",
   "note": "0.4–1.1 (台灣種類)",
   "min": 0.46,
   "max": 1.37,
   "pad": 0.0364,
   "values": {
    "actoni": {
     "min": 0.46,
     "max": 0.46,
     "raw": "0.46"
    },
    "arakawae": {
     "min": 1.37,
     "max": 1.37,
     "raw": "1.37"
    },
    "homotomus": {
     "min": 0.64,
     "max": 0.64,
     "raw": "0.64"
    },
    "jacobsoni": {
     "min": 0.47,
     "max": 0.56,
     "raw": "0.47–0.56"
    },
    "lungchiensis": {
     "min": 0.86,
     "max": 0.86,
     "raw": "0.86"
    },
    "palpifer": {
     "min": 0.62,
     "max": 0.62,
     "raw": "0.62"
    },
    "oxystoma": {
     "min": 0.69,
     "max": 0.69,
     "raw": "0.69"
    },
    "sumatrae": {
     "min": 0.51,
     "max": 0.57,
     "raw": "0.51–0.57"
    },
    "tainanus": {
     "min": 0.5,
     "max": 0.56,
     "raw": "0.50–0.56"
    }
   }
  },
  {
   "id": "n_5",
   "region": "Mouthpart",
   "name": "大顎齒數",
   "nameEn": "Mandible teeth count",
   "type": "num",
   "unit": "顆",
   "note": "5–25",
   "min": 7.0,
   "max": 19.0,
   "pad": 0.5,
   "values": {
    "actoni": {
     "min": 13.0,
     "max": 14.0,
     "raw": "13–14"
    },
    "arakawae": {
     "min": 13.0,
     "max": 16.0,
     "raw": "13–16"
    },
    "homotomus": {
     "min": 12.0,
     "max": 15.0,
     "raw": "12–15"
    },
    "jacobsoni": {
     "min": 14.0,
     "max": 14.0,
     "raw": "14"
    },
    "lungchiensis": {
     "min": 16.0,
     "max": 16.0,
     "raw": "16"
    },
    "palpifer": {
     "min": 7.0,
     "max": 7.0,
     "raw": "7"
    },
    "oxystoma": {
     "min": 14.0,
     "max": 14.0,
     "raw": "14"
    },
    "sumatrae": {
     "min": 18.0,
     "max": 19.0,
     "raw": "18–19"
    },
    "tainanus": {
     "min": 15.0,
     "max": 16.0,
     "raw": "15–16"
    }
   }
  },
  {
   "id": "n_6",
   "region": "Mouthpart",
   "name": "下顎齒數",
   "nameEn": "Maxilla teeth count",
   "type": "num",
   "unit": "顆",
   "note": "5–25",
   "min": 12.0,
   "max": 25.0,
   "pad": 0.52,
   "values": {
    "actoni": {
     "min": 13.0,
     "max": 14.0,
     "raw": "13–14"
    },
    "arakawae": {
     "min": 25.0,
     "max": 25.0,
     "raw": "25"
    },
    "homotomus": {
     "min": 16.0,
     "max": 19.0,
     "raw": "16–19"
    },
    "jacobsoni": {
     "min": 15.0,
     "max": 15.0,
     "raw": "15"
    },
    "lungchiensis": {
     "min": 18.0,
     "max": 18.0,
     "raw": "18"
    },
    "palpifer": {
     "min": 12.0,
     "max": 12.0,
     "raw": "12"
    },
    "oxystoma": {
     "min": 16.0,
     "max": 16.0,
     "raw": "16"
    },
    "sumatrae": {
     "min": 18.0,
     "max": 20.0,
     "raw": "18–20"
    },
    "tainanus": {
     "min": 15.0,
     "max": 17.0,
     "raw": "15–17"
    }
   }
  },
  {
   "id": "n_7",
   "region": "Hind leg",
   "name": "後足脛節鬃數目",
   "nameEn": "Hindtibial comb spines",
   "type": "num",
   "unit": "根",
   "note": "3–6根（台灣種類多4–5根）",
   "min": 4.0,
   "max": 6.0,
   "pad": 0.5,
   "values": {
    "actoni": {
     "min": 5.0,
     "max": 5.0,
     "raw": "5"
    },
    "arakawae": {
     "min": 4.0,
     "max": 4.0,
     "raw": "4"
    },
    "homotomus": {
     "min": 5.0,
     "max": 5.0,
     "raw": "5"
    },
    "jacobsoni": {
     "min": 5.0,
     "max": 5.0,
     "raw": "5"
    },
    "lungchiensis": {
     "min": 6.0,
     "max": 6.0,
     "raw": "6"
    },
    "palpifer": {
     "min": 4.0,
     "max": 4.0,
     "raw": "4"
    },
    "oxystoma": {
     "min": 4.0,
     "max": 4.0,
     "raw": "4"
    },
    "sumatrae": {
     "min": 5.0,
     "max": 5.0,
     "raw": "5"
    },
    "tainanus": {
     "min": 5.0,
     "max": 5.0,
     "raw": "5"
    }
   }
  },
  {
   "id": "c_8",
   "region": "Hind leg",
   "name": "後足脛節鬃最長",
   "nameEn": "Hindtibial comb spine longest",
   "type": "cat",
   "note": "1 or 2",
   "states": [
    "第 1 根最長",
    "第 2 根最長"
   ],
   "values": {
    "actoni": {
     "state": "第 1 根最長",
     "raw": "1"
    },
    "arakawae": {
     "state": "第 2 根最長",
     "raw": "2"
    },
    "homotomus": {
     "state": "第 2 根最長",
     "raw": "2"
    },
    "jacobsoni": {
     "state": "第 1 根最長",
     "raw": "1"
    },
    "lungchiensis": {
     "state": "第 2 根最長",
     "raw": "2"
    },
    "palpifer": {
     "state": "第 2 根最長",
     "raw": "2"
    },
    "oxystoma": {
     "state": "第 1 根最長",
     "raw": "1"
    },
    "sumatrae": {
     "state": "第 2 根最長",
     "raw": "2"
    },
    "tainanus": {
     "state": "第 1 根最長",
     "raw": "1"
    }
   }
  },
  {
   "id": "n_9",
   "region": "Wing",
   "name": "翅長",
   "nameEn": "Wing length",
   "type": "num",
   "unit": "mm",
   "note": "0.6–2.2 mm (台灣種類)",
   "min": 0.66,
   "max": 1.64,
   "pad": 0.0392,
   "values": {
    "actoni": {
     "min": 0.66,
     "max": 0.74,
     "raw": "0.66–0.74 mm"
    },
    "arakawae": {
     "min": 0.97,
     "max": 1.04,
     "raw": "0.97–1.04 mm"
    },
    "homotomus": {
     "min": 1.48,
     "max": 1.48,
     "raw": "1.48 mm"
    },
    "jacobsoni": {
     "min": 0.84,
     "max": 0.99,
     "raw": "0.84–0.99 mm"
    },
    "lungchiensis": {
     "min": 1.64,
     "max": 1.64,
     "raw": "1.64 mm"
    },
    "palpifer": {
     "min": 1.06,
     "max": 1.06,
     "raw": "1.06 mm"
    },
    "oxystoma": {
     "min": 0.86,
     "max": 0.86,
     "raw": "0.86 mm"
    },
    "sumatrae": {
     "min": 1.19,
     "max": 1.23,
     "raw": "1.19–1.23 mm"
    },
    "tainanus": {
     "min": 0.85,
     "max": 1.16,
     "raw": "0.85–1.16 mm"
    }
   }
  },
  {
   "id": "n_10",
   "region": "Wing",
   "name": "CR 前緣比",
   "nameEn": "Costal ratio",
   "type": "num",
   "unit": "",
   "note": "0.55–0.72 (台灣種類)",
   "min": 0.52,
   "max": 0.71,
   "pad": 0.01,
   "values": {
    "actoni": {
     "min": 0.54,
     "max": 0.55,
     "raw": "0.54–0.55"
    },
    "arakawae": {
     "min": 0.61,
     "max": 0.61,
     "raw": "0.61"
    },
    "homotomus": {
     "min": 0.58,
     "max": 0.58,
     "raw": "0.58"
    },
    "jacobsoni": {
     "min": 0.52,
     "max": 0.64,
     "raw": "0.52–0.64"
    },
    "lungchiensis": {
     "min": 0.65,
     "max": 0.65,
     "raw": "0.65"
    },
    "palpifer": {
     "min": 0.71,
     "max": 0.71,
     "raw": "0.71"
    },
    "oxystoma": {
     "min": 0.56,
     "max": 0.56,
     "raw": "0.56"
    },
    "sumatrae": {
     "min": 0.54,
     "max": 0.55,
     "raw": "0.54–0.55"
    },
    "tainanus": {
     "min": 0.52,
     "max": 0.61,
     "raw": "0.52–0.61"
    }
   }
  },
  {
   "id": "c_11",
   "region": "Spermathecae",
   "name": "精囊數目",
   "nameEn": "Number of spermathecae",
   "type": "cat",
   "note": "3個發育完全 / 2+1退化環 / 2個發育完全 / 1個",
   "states": [
    "1 個",
    "2 個",
    "3 個"
   ],
   "values": {
    "actoni": {
     "state": "2 個",
     "raw": "2"
    },
    "arakawae": {
     "state": "1 個",
     "raw": "1"
    },
    "homotomus": {
     "state": "1 個",
     "raw": "1"
    },
    "jacobsoni": {
     "state": "2 個",
     "raw": "2"
    },
    "lungchiensis": {
     "state": "2 個",
     "raw": "2"
    },
    "palpifer": {
     "state": "3 個",
     "raw": "3"
    },
    "oxystoma": {
     "state": "2 個",
     "raw": "2"
    },
    "sumatrae": {
     "state": "2 個",
     "raw": "2"
    },
    "tainanus": {
     "state": "2 個",
     "raw": "2"
    }
   }
  }
 ],
 "reference": [
  {
   "region": "Eyes",
   "name": "複眼相連",
   "nameEn": "Eye contiguity",
   "values": {
    "actoni": "1",
    "arakawae": "0",
    "homotomus": "0",
    "jacobsoni": "1",
    "lungchiensis": "2",
    "palpifer": "0",
    "oxystoma": "0",
    "sumatrae": "3",
    "tainanus": "1"
   }
  },
  {
   "region": "Antenna",
   "name": "感覺毛分布節段",
   "nameEn": "Sensilla coeloconica (SC) segments",
   "values": {
    "actoni": "3, 11–15",
    "arakawae": "3–14",
    "homotomus": "3, 8–10",
    "jacobsoni": "3, 11–15",
    "lungchiensis": "3, 11–15",
    "palpifer": "3, 11–15",
    "oxystoma": "3, 8–10",
    "sumatrae": "3, 11–15",
    "tainanus": "3, 11–15"
   }
  },
  {
   "region": "Palpus",
   "name": "第3節形態",
   "nameEn": "3rd segment shape",
   "values": {
    "actoni": "粗短膨大",
    "arakawae": "粗短膨大",
    "homotomus": "些微膨大",
    "jacobsoni": "中段膨大",
    "lungchiensis": "略微膨大",
    "palpifer": "稍微膨大",
    "oxystoma": "中段膨大",
    "sumatrae": "近端稍微膨大",
    "tainanus": "稍微膨大"
   }
  },
  {
   "region": "Palpus",
   "name": "感覺窩位置 (接近端部)",
   "nameEn": "",
   "values": {
    "actoni": "中段",
    "arakawae": "端部",
    "homotomus": "端部",
    "jacobsoni": "中段",
    "lungchiensis": null,
    "palpifer": "端部",
    "oxystoma": "中段",
    "sumatrae": "近端部1/3",
    "tainanus": "近端部1/3"
   }
  },
  {
   "region": "Mouthpart",
   "name": "大顎齒形",
   "nameEn": "Mandible teeth shape",
   "values": {
    "actoni": null,
    "arakawae": null,
    "homotomus": null,
    "jacobsoni": null,
    "lungchiensis": null,
    "palpifer": null,
    "oxystoma": null,
    "sumatrae": null,
    "tainanus": null
   }
  },
  {
   "region": "Mesonotum",
   "name": "中胸背板底色",
   "nameEn": "Mesonotum ground color",
   "values": {
    "actoni": "全深褐",
    "arakawae": "褐色",
    "homotomus": "褐色",
    "jacobsoni": "暗褐色",
    "lungchiensis": "暗褐色",
    "palpifer": "淡黃色（楯板）",
    "oxystoma": "暗褐色",
    "sumatrae": "暗褐色",
    "tainanus": "暗褐色"
   }
  },
  {
   "region": "Mesonotum",
   "name": "中胸背板斑紋",
   "nameEn": "Mesonotum pattern",
   "values": {
    "actoni": "全深褐",
    "arakawae": "褐色",
    "homotomus": "褐色",
    "jacobsoni": "暗褐色",
    "lungchiensis": "暗褐色",
    "palpifer": "淡黃色",
    "oxystoma": "暗褐色",
    "sumatrae": "暗褐色",
    "tainanus": "暗褐色"
   }
  },
  {
   "region": "Mesonotum",
   "name": "楯片顏色",
   "nameEn": "scutum",
   "values": {
    "actoni": "全深褐",
    "arakawae": "褐色",
    "homotomus": "褐色",
    "jacobsoni": "暗褐色",
    "lungchiensis": "暗褐色",
    "palpifer": "暗褐色",
    "oxystoma": "暗褐色",
    "sumatrae": "暗褐色",
    "tainanus": "暗褐色"
   }
  },
  {
   "region": "Halter",
   "name": "平衡棒色澤",
   "nameEn": "Halter color",
   "values": {
    "actoni": "淡褐色",
    "arakawae": "褐色",
    "homotomus": "淡黃色",
    "jacobsoni": "淡褐色",
    "lungchiensis": "淡黃色",
    "palpifer": "淡黃色",
    "oxystoma": "淡褐色",
    "sumatrae": "淡褐色",
    "tainanus": "淡褐色"
   }
  },
  {
   "region": "Hind leg",
   "name": "後腿節色澤",
   "nameEn": "Hind femur color",
   "values": {
    "actoni": "淡褐色，腿節基部淡色帶",
    "arakawae": "褐色，腿節端部+脛節基部淡色帶",
    "homotomus": "褐色，腿節基部+脛節基部淡色帶",
    "jacobsoni": "褐色，後腿節端部無淡色帶",
    "lungchiensis": "褐色，脛節基部+端部淡色帶",
    "palpifer": "深褐色，無膝部淡色帶",
    "oxystoma": "褐色，腿節端部+脛節基部淡色帶",
    "sumatrae": "褐色，腿節基部+脛節基部+端部淡色帶",
    "tainanus": "褐色，腿節端部+脛節基部淡色帶"
   }
  },
  {
   "region": "Wing",
   "name": "第1前緣淡斑",
   "nameEn": "1st costal pale spot",
   "values": {
    "actoni": "覆蓋徑中橫脈及第1徑室基部約1/2",
    "arakawae": "覆蓋徑中橫脈、基室末端與第5徑室基部",
    "homotomus": "覆蓋徑中橫脈、基室末端與第5徑室基部",
    "jacobsoni": "覆蓋徑中橫脈及第1徑室基部",
    "lungchiensis": "覆蓋徑中橫脈、基室末端與第5徑室基部",
    "palpifer": "覆蓋徑中橫脈及第1徑室基部約1/2",
    "oxystoma": "覆蓋徑中橫脈、基室末端與第5徑室基部",
    "sumatrae": "狹窄，覆蓋徑中橫脈及第1徑室1/3",
    "tainanus": "覆蓋徑中橫脈及第1徑室基部"
   }
  },
  {
   "region": "Wing",
   "name": "第2前緣淡斑",
   "nameEn": "2nd costal pale spot",
   "values": {
    "actoni": "位於第2徑室外側，未抵第1中脈",
    "arakawae": "覆蓋第5徑室近第2徑室處，不覆蓋第2徑室",
    "homotomus": "覆蓋第5徑室近第2徑室處，不覆蓋第2徑室",
    "jacobsoni": "覆蓋第2徑室端部，未抵第1中脈",
    "lungchiensis": "覆蓋第2徑室端部約1/2",
    "palpifer": "覆蓋第2徑室端部1/2",
    "oxystoma": "包圍第2徑室外緣（模糊淡色帶）",
    "sumatrae": "小，覆蓋第2徑室端部1/2",
    "tainanus": "覆蓋第2徑室端部，幾乎抵第1中脈"
   }
  },
  {
   "region": "Wing",
   "name": "第3前緣淡斑",
   "nameEn": "3rd costal pale spot",
   "values": {
    "actoni": "位於翅緣，未抵第1中脈",
    "arakawae": "小而圓，位於第5徑室近翅端，抵於翅緣",
    "homotomus": "不抵翅緣",
    "jacobsoni": "位於翅緣內側，未抵第1中脈",
    "lungchiensis": "形狀不規則，中段略收縮，抵翅緣",
    "palpifer": "翅端大弧形淡斑，跨R5/M1/M2",
    "oxystoma": "形狀不規則，中段略收縮，抵翅緣",
    "sumatrae": "位於翅緣內側，未抵翅緣",
    "tainanus": "大，抵第1中脈且抵翅緣"
   }
  },
  {
   "region": "Wing",
   "name": "M4室",
   "nameEn": "Cell M4 pattern",
   "values": {
    "actoni": "中部至端部具大淡斑",
    "arakawae": "端部具淡斑",
    "homotomus": "端部具淡斑",
    "jacobsoni": "端部具淡斑",
    "lungchiensis": "端部具淡斑",
    "palpifer": "端部具淡斑（不明顯）",
    "oxystoma": "端部具淡斑",
    "sumatrae": "端部具小圓形淡斑",
    "tainanus": "端部具淡斑"
   }
  },
  {
   "region": "Wing",
   "name": "M1室",
   "nameEn": "Cell M1 pattern",
   "values": {
    "actoni": "基部及端部各有一淡斑",
    "arakawae": "中部及近端部各具一小淡斑",
    "homotomus": "中部及近端部各具一小淡斑，中央部具大淡斑",
    "jacobsoni": "中部及近端部各具一小淡斑",
    "lungchiensis": "中部及近端部各具一小淡斑",
    "palpifer": "有模糊淡色帶",
    "oxystoma": "中部及近端部各具一小淡斑",
    "sumatrae": "中部與接近端部各有一小淡斑",
    "tainanus": "中部及近端部各具一大淡斑"
   }
  },
  {
   "region": "Wing",
   "name": "M2室",
   "nameEn": "Cell M2 pattern",
   "values": {
    "actoni": "自基部帶狀淡斑延伸至翅緣",
    "arakawae": "中部及近端部各具一小淡斑",
    "homotomus": "中部及近端部各具一小淡斑",
    "jacobsoni": "自基部細長帶狀淡斑延伸至近翅緣",
    "lungchiensis": "中部連接中肘叉脈一淡斑",
    "palpifer": "中部至端部3個小淡斑",
    "oxystoma": "第3中室向翅基方向基部與中部各具一小淡斑",
    "sumatrae": "中部至端部3個小淡斑",
    "tainanus": "自基部細長帶狀淡斑延伸至近翅緣"
   }
  },
  {
   "region": "Wing",
   "name": "R5室端色",
   "nameEn": "Cell R5 apex",
   "values": {
    "actoni": null,
    "arakawae": null,
    "homotomus": null,
    "jacobsoni": null,
    "lungchiensis": null,
    "palpifer": null,
    "oxystoma": null,
    "sumatrae": null,
    "tainanus": null
   }
  },
  {
   "region": "Wing",
   "name": "M1+M2暗斑",
   "nameEn": "M1+M2 dark spots",
   "values": {
    "actoni": null,
    "arakawae": null,
    "homotomus": null,
    "jacobsoni": null,
    "lungchiensis": null,
    "palpifer": null,
    "oxystoma": null,
    "sumatrae": null,
    "tainanus": null
   }
  },
  {
   "region": "Wing",
   "name": "翅基淡區",
   "nameEn": "Basal pale area",
   "values": {
    "actoni": "大，延伸至臀室",
    "arakawae": "小而圓，僅基室基部和中室基部",
    "homotomus": "大，由基室延伸至臀室中間",
    "jacobsoni": "小而不規則，僅基室和中室基部",
    "lungchiensis": "延伸至臀室基部",
    "palpifer": "延伸至臀室基部",
    "oxystoma": "小，僅基室1/2與中室基部",
    "sumatrae": "大、不規則，由基室延伸至臀室",
    "tainanus": "大，由基室延伸至臀室"
   }
  },
  {
   "region": "Wing",
   "name": "大毛分布範圍",
   "nameEn": "Macrotrichia distribution",
   "values": {
    "actoni": null,
    "arakawae": null,
    "homotomus": null,
    "jacobsoni": null,
    "lungchiensis": null,
    "palpifer": null,
    "oxystoma": null,
    "sumatrae": null,
    "tainanus": null
   }
  },
  {
   "region": "Spermathecae",
   "name": "精囊形狀",
   "nameEn": "Spermatheca shape",
   "values": {
    "actoni": "卵形",
    "arakawae": "梨形（延長，無頸）",
    "homotomus": "梨形（無頸）",
    "jacobsoni": "卵形",
    "lungchiensis": "有頸但不明顯",
    "palpifer": "圓形（中間最大）",
    "oxystoma": "卵形",
    "sumatrae": "近圓形（具短柄）",
    "tainanus": "近圓形"
   }
  },
  {
   "region": "Spermathecae",
   "name": "精囊大小",
   "nameEn": "size",
   "values": {
    "actoni": "幾乎等大",
    "arakawae": "NA（僅1個）",
    "homotomus": "NA（僅1個）",
    "jacobsoni": "幾乎等大",
    "lungchiensis": "大小略有不同",
    "palpifer": "不等大（中間最大）",
    "oxystoma": "略等大",
    "sumatrae": "幾乎等大",
    "tainanus": "幾乎等大"
   }
  }
 ]
};
