// Auto-generated by gen_species_plate.py - do not edit manually
window.SPECIES_PLATE = [
 {
  "id": "actoni",
  "sci": "Culicoides actoni",
  "zh": "阿氏庫蠓"
 },
 {
  "id": "arakawae",
  "sci": "Culicoides arakawae",
  "zh": "荒川庫蠓"
 },
 {
  "id": "clavipalpis",
  "sci": "Culicoides clavipalpis",
  "zh": "棒鬚庫蠓"
 },
 {
  "id": "dentiformis",
  "sci": "Culicoides dentiformis",
  "zh": "齒紋庫蠓"
 },
 {
  "id": "dubius",
  "sci": "Culicoides dubius",
  "zh": "疑念庫蠓"
 },
 {
  "id": "homotomus",
  "sci": "Culicoides homotomus",
  "zh": "原野庫蠓"
 },
 {
  "id": "innoxius",
  "sci": "Culicoides innoxius",
  "zh": "無害庫蠓"
 },
 {
  "id": "jacobsoni",
  "sci": "Culicoides jacobsoni",
  "zh": "加氏庫蠓"
 },
 {
  "id": "lungchiensis",
  "sci": "Culicoides lungchiensis",
  "zh": "龍溪庫蠓"
 },
 {
  "id": "malayae__kinabaluensis__cameronensis",
  "sci": "Culicoides malayae / kinabaluensis / cameronensis",
  "zh": "近似馬來庫蠓"
 },
 {
  "id": "mcdonaldi",
  "sci": "Culicoides mcdonaldi",
  "zh": "棲山庫蠓/麥氏庫蠓"
 },
 {
  "id": "orientalis",
  "sci": "Culicoides orientalis",
  "zh": "東方庫蠓"
 },
 {
  "id": "oxystoma",
  "sci": "Culicoides oxystoma",
  "zh": "嗜牛庫蠓"
 },
 {
  "id": "sumatrae",
  "sci": "Culicoides sumatrae?",
  "zh": "蘇島庫蠓"
 },
 {
  "id": "tainanus",
  "sci": "Culicoides tainanus",
  "zh": "台南庫蠓"
 },
 {
  "id": "tamada",
  "sci": "Culicoides tamada",
  "zh": "平淡庫蠓"
 },
 {
  "id": "verbosus",
  "sci": "Culicoides verbosus",
  "zh": "婆娑庫蠓"
 },
 {
  "id": "應該是帶鬚",
  "sci": "Culicoides 應該是帶鬚",
  "zh": "牛場三囊亞屬"
 },
 {
  "id": "應該是褐肩",
  "sci": "Culicoides 應該是褐肩",
  "zh": "牛場三囊亞屬"
 },
 {
  "id": "quadripunctata",
  "sci": "Alluaudomyia quadripunctata",
  "zh": "阿蠓屬"
 },
 {
  "id": "n.sp",
  "sci": "Forcipomyia n.sp",
  "zh": "盲蛛鋏蠓"
 }
];
